MyDevCard/Models/Article.cs
namespace MyDevCard.Models;

public class Article
{
    public Article(long id, string name, string title, string des)
    {
        Id = id;
        Name = name;
        Title = title;
        Des = des;
    }

    public long Id { get; set; }
    public string Name { get; set; }
    public string Title { get; set; }
    public string Des { get; set; }
}

MyDevCard/Models/Contact.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MyDevCard.Models;

public class Contact
{
    // public Contact(string name, string email, string message, string service)
    // {
    //     Name = name;
    //     Email = email;
    //     Message = message;
    //     Service = service;
    // }

    [Required(ErrorMessage = "مقدار این فیلد اجباری است")]
    [MaxLength(10, ErrorMessage = "تعداد کاراکتر باید از ۱۰ کوچکتر باشد")]
    [MinLength(3, ErrorMessage = "تعداد کاراکتر باید از ۳ بزرگتر باشد")]
    public string Name { get; set; }
    [EmailAddress(ErrorMessage = "ایمیل معتبر نیست")]
    [Required(ErrorMessage = "مقدار این فیلد اجباری است")]
    public string Email { get; set; }
    public string Message { get; set; }
    public string Service { get; set; }
    public SelectList Services { get; set; }
}

MyDevCard/Models/ErrorViewModel.cs
namespace MyDevCard.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MyDevCard/Models/Project.cs
namespace MyDevCard.Models;

public class Project
{
    public Project(long id, string name, string title, string des)
    {
        Id = id;
        Name = name;
        Title = title;
        Des = des;
    }

    public long Id { get; set; }
    public string Name { get; set; }
    public string Title { get; set; }
    public string Des { get; set; }
}

MyDevCard/Models/Service.cs
namespace MyDevCard.Models;

public class Service
{
    public Service(int id, string name)
    {
        Id = id;
        Name = name;
    }

    public int Id { get; set; }
    public string Name { get; set; }
}

MyDevCard/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyDevCard.Models;

namespace MyDevCard.Controllers;

public class HomeController : Controller
{

    public readonly List<Service> _Services = new List<Service>()
    {
        new Service(1, "ali"),
        new Service(2, "ali"),
        new Service(3, "ali"),
        new Service(4, "ali"),
        new Service(5, "ali"),
        new Service(6, "ali"),

    };
    public IActionResult Index()
    {
        return View();
    }

    [HttpGet]
    public IActionResult Contact()
    {
        var contact = new Contact()
        {
            Services = new SelectList(_Services, "Id", "Name")
        };
        return View(contact);
    }

    [HttpPost]
    public IActionResult Contact(Contact form)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.Error = "اطلاعات وارد شده صحیح نیست دوباره تلاش کنید";
            return View(form);
        }
        else
        {
            ViewBag.Success = "پیغام شما ارسال شد با تشکر";
            return View();
        }
        
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MyDevCard/ViewComponents/ArticleViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyDevCard.Models;

namespace MyDevCard.ViewComponents;

public class ArticleViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var article = new List<Article>()
        {
            new Article(1, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(2, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(3, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(4, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(5, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(6, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(7, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(8, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            new Article(9, "bernard", "fwiewfejewfjn", "saldldskdask sadjjd as"),
            
            
        };
        return View("_article", article);
    }
}

MyDevCard/ViewComponents/ProjectViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MyDevCard.Models;

namespace MyDevCard.ViewComponents;

public class ProjectViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var projects = new List<Project>()
        {
            new Project(1, "senegal", "Senegal", "Maldiv is best country in Dream"),
            new Project(2, "senegal", "Senegal", "Maldiv is best country in Dream"),
            new Project(3, "senegal", "Senegal", "Maldiv is best country in Dream"),
            new Project(4, "senegal", "Senegal", "Maldiv is best country in Dream"),
            new Project(5, "senegal", "Senegal", "Maldiv is best country in Dream"),
            new Project(6, "senegal", "Senegal", "Maldiv is best country in Dream")

        };
        return View("_Projects", projects);

    }
}

MyDevCard/Views/Home/Components/Article/_article.cshtml
@model IEnumerable<MyDevCard.Models.Article>


<!DOCTYPE html>

<section class="latest-blog-section p-3 p-lg-5">
    <div class="container">
        <h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>

@foreach (var article in Model)
{
    <div class="row">
    <div class="col-md-4 mb-5">
        <div class="card blog-post-card">
            <img class="card-img-top" src="~/assets/images/blog/blog-post-thumb-card-1.jpg" alt=@article.Name title=@article.Des >
            <div class="card-body">
                <h5 class="card-title">
                    <a class="theme-link" href="blog-post.html">@article.Name
                        Frameworks</a></h5>
                <p class="card-text">@article.Des</p>
<p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

</div>
</div>
</div>
    </div>

        }
    </div>
    
</section>

MyDevCard/Views/Home/Components/Project/_Projects.cshtml
@model IEnumerable<MyDevCard.Models.Project>
<thead>
@foreach (var project in Model)
{
    <div class="col-md-6 mb-5">
        <div class="card project-card">
            <div class="row no-gutters">
                <div class="col-lg-4 card-img-holder">
                    <img src="~/assets/images/project/project-4.jpg" class="card-img" alt="@project.Name" title="@project.Des">
                </div>
                <div class="col-lg-8">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="project.html" class="theme-link">Project
                                Heading</a></h5>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
                            Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
                            ridiculus mus. </p>
                        <p class="card-text"><small class="text-muted">Client: Uber</small></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
</thead>

MyDevCard/Views/Home/Contact.cshtml
@model Contact
<!DOCTYPE html>

	<div class="main-wrapper">
		<div class="cta-section theme-bg-light py-5">
			< class="container text-center single-col-max-width">
				<h2 class="heading">ارتباط با ما</h2>
				<div class="intro">
					<p>شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
						نوشته و ارسال کنید.</p>
					<p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
					<ul class="list-inline mb-0">
						<li class="list-inline-item mb-3"><a class="twitter" href="#"><i
									class="fab fa-twitter fa-fw fa-lg"></i></a></li>

						<li class="list-inline-item mb-3"><a class="linkedin" href="#"><i
									class="fab fa-linkedin-in fa-fw fa-lg"></i></a></li>
						<li class="list-inline-item mb-3"><a class="github" href="#"><i
									class="fab fa-github-alt fa-fw fa-lg"></i></a></li>
						<li class="list-inline-item"><a class="instagram" href="#"><i
									class="fab fa-instagram fa-fw fa-lg"></i></a></li>
						<li class="list-inline-item mb-3"><a class="stack-overflow" href="#"><i
									class="fab fa-stack-overflow fa-fw fa-lg"></i></a></li>
						<li class="list-inline-item mb-3"><a class="medium" href="#"><i
									class="fab fa-medium-m fa-fw fa-lg"></i></a></li>
						<li class="list-inline-item mb-3"><a class="codepen" href="#"><i
									class="fab fa-codepen fa-fw fa-lg"></i></a></li>
					</ul>
				</div>
			<section class="contact-section px-3 py-5 p-md-5">
				<div class="container">
					
					@if (!string.IsNullOrWhiteSpace(ViewBag.Success))
					{
						<div class="bg-success">
							<p>@ViewBag.Success</p>
						</div>
					}
					
					<form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
						<h3 class="text-center mb-3">در دسترس باشید!</h3>
						<div class="form-row">
							<div class="form-group col-md-6">
								<label class="sr-only" asp-for="Name">نام</label>
								<input type="text" class="form-control" id="cname" name="name" placeholder="نام" asp-for="Name"
								       minlength="2" required="" aria-required="true">
							</div>
							<div class="form-group col-md-6">
								<label class="sr-only" asp-for="Email">ایمیل</label>
								<span asp-validation-for="Email"></span>
								<input type="email" class="form-control" id="cemail" asp-for="Email" name="email" placeholder="ایمیل" asp-for="Email"
								       required="" aria-required="true">
							</div>
							<div class="form-group col-12">
								<select id="services" class="custom-select" name="services" asp-for="Service" asp-items="Model.Services">
									<option value="0" selected>سرویس مورد نظر خود را انتخاب کنید...</option>
									
									
								</select>
							</div>
							<div class="form-group col-12">
								<label class="sr-only" asp-for="Message">پیغام شما</label>
								<textarea class="form-control" id="cmessage" name="message" asp-for="Message"
								placeholder="پیغام خود را وارد نمایید ..." rows="10" required=""
								aria-required="true"></textarea>
							</div>
							<div class="form-group col-12">
								<button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
							</div>
						</div>
					</form>
				</div>
			</section>
		</div>

</div>

MyDevCard/Views/Home/Index.cshtml
	<div class="main-wrapper">
		<section class="about-me-section p-3 p-lg-5 theme-bg-light">
			<div class="container">
				<div class="profile-teaser media flex-column flex-lg-row">
					<img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="~/assets/images/me.jpeg" alt="">
					<div class="media-body">
						<h2 class="name font-weight-bold mb-1">پویان نظری</h2>
						<div class="tagline mb-3">برنامه نویس جونیور</div>
						<div class="bio mb-4">لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
							طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
							جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
						</div>
						<div class="mb-4">
							<a class="btn btn-primary mr-2 mb-3" href="http://www.atriya.com"><i
									class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">برو
									به </span> آتریا</a>
							<a class="btn btn-secondary mb-3" href="#">
								<i class="fas fa-file-alt ml-2"></i>
								<span class="d-none d-md-inline">مشاهده </span> نمونه کارها</a>
						</div>
					</div>

				</div>
			</div>
		</section>
		<section class="featured-section p-3 p-lg-5">
			<div class="container">
				<h2 class="section-title font-weight-bold mb-5">خاص ترین پروژه ها</h2>
				<div class="row">
					<div class="col-md-6 mb-5">
						<div class="card project-card">
							<div class="row no-gutters">
								<div class="col-lg-4 card-img-holder">
									<img src="~/assets/images/project/project-1.jpg" class="card-img" alt="image">
								</div>
								<div class="col-lg-8">
									<div class="card-body">
										<h5 class="card-title"><a href="project.html" class="theme-link">Project
												Heading</a></h5>
										<p class="card-text">Project intro lorem ipsum dolor sit amet, consectetuer
											adipiscing elit. Cum sociis natoque penatibus et magnis dis parturient
											montes.</p>
										<p class="card-text"><small class="text-muted">Client: Google</small></p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6 mb-5">
						<div class="card project-card">
							<div class="row no-gutters">
								<div class="col-lg-4 card-img-holder">
									<img src="~/assets/images/project/project-2.jpg" class="card-img" alt="image">
								</div>
								<div class="col-lg-8">
									<div class="card-body">
										<h5 class="card-title"><a href="project.html" class="theme-link">Project
												Heading</a></h5>
										<p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
											Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
											ridiculus mus. </p>
										<p class="card-text"><small class="text-muted">Client: Dropbox</small></p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6 mb-5">
						<div class="card project-card">
							<div class="row no-gutters">
								<div class="col-lg-4 card-img-holder">
									<img src="~/assets/images/project/project-3.jpg" class="card-img" alt="image">
								</div>
								<div class="col-lg-8">
									<div class="card-body">
										<h5 class="card-title"><a href="project.html" class="theme-link">Project
												Heading</a></h5>
										<p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
											Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
											ridiculus mus. </p>
										<p class="card-text"><small class="text-muted">Client: Google</small></p>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-6 mb-5">
						<div class="card project-card">
							<div class="row no-gutters">
								<div class="col-lg-4 card-img-holder">
									<img src="~/assets/images/project/project-4.jpg" class="card-img" alt="image">
								</div>
								<div class="col-lg-8">
									<div class="card-body">
										<h5 class="card-title"><a href="project.html" class="theme-link">Project
												Heading</a></h5>
										<p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit.
											Cum sociis natoque penatibus et magnis dis parturient montes, nascetur
											ridiculus mus. </p>
										<p class="card-text"><small class="text-muted">Client: Uber</small></p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

	@await Component.InvokeAsync("Project")
	
	<div class="container">
			<hr>
		</div>

		<section class="latest-blog-section p-3 p-lg-5">
			<div class="container">
				<h2 class="section-title font-weight-bold mb-5">آخرین مقالات</h2>
				<div class="row">
					<div class="col-md-4 mb-5">
						<div class="card blog-post-card">
							<img class="card-img-top" src="~/assets/images/blog/blog-post-thumb-card-1.jpg" alt="image">
							<div class="card-body">
								<h5 class="card-title"><a class="theme-link" href="blog-post.html">Top 3 JavaScript
										Frameworks</a></h5>
								<p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
									commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis
									parturient...</p>
								<p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>

							</div>
						</div>
					</div>
					<div class="col-md-4 mb-5">
						<div class="card blog-post-card">
							<img class="card-img-top" src="~/assets/images/blog/blog-post-thumb-card-2.jpg" alt="image">
							<div class="card-body">
								<h5 class="card-title"><a class="theme-link" href="blog-post.html">About Remote
										Working</a></h5>
								<p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
									commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis
									parturient...</p>
								<p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>
							</div>
						</div>
					</div>
					<div class="col-md-4 mb-5">
						<div class="card blog-post-card">
							<img class="card-img-top" src="~/assets/images/blog/blog-post-thumb-card-3.jpg" alt="image">
							<div class="card-body">
								<h5 class="card-title"><a class="theme-link" href="blog-post.html">A Guide to Becoming a
										Full-Stack Developer</a></h5>
								<p class="card-text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
									commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis
									parturient...</p>
								<p class="mb-0"><a class="more-link" href="blog-post.html">ادامه مطلب</a></p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>

@await Component.InvokeAsync("Article")
	</div> 

MyDevCard/Views/Shared/Footer.cshtml
<footer class="footer text-center py-4">
    <small class="copyright">تولید شده توسط &copy; <a href="http://www.atriya.com" target="_blank">موسسه آموزشی
            آتریا</a></small>
</footer>

MyDevCard/Views/Shared/Header.cshtml
<header class="header text-center">
    <div class="force-overflow">
        <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">حسین عباس آبادی</a></h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        
        
        <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto" src="~/assets/images/me.jpeg" alt="image">

                    <div class="bio mb-3">سلام پویان نظری هستم به وبسایت شخصی من خوش آمدید.</div>
                    <ul class="social-list list-inline py-2 mx-auto">
                        <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a>
                        </li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
                    </ul>
                    <hr>
                </div>
                <ul class="navbar-nav flex-column text-right">
                    <li class="nav-item">
                        <a class="nav-link" href="index.html"><i class="fas fa-user fa-fw ml-2"></i>صفحه اصلی<span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-action="Contact" asp-controller="Home""><i
                                class="fas fa-envelope-open-text fa-fw ml-2"></i>ارتباط با من</a>
                    </li>
                </ul>
            </div>
    </div>
    </nav>
    </div>
</header>

MyDevCard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa">

<head>
    <title>My First Project</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="favicon.ico">

    <script defer src="~/assets/fontawesome/js/all.js"></script>
    <link id="theme-style" rel="stylesheet" href="~/assets/css/theme-1.css">
    <link id="theme-style" rel="stylesheet" href="~/assets/css/style.css">

</head>

<body>
<partial name="Header"/>
@RenderBody()

<div class="main-wrapper">
    <partial name="Footer"/>
</div>

<!-- Javascript -->
<script src="~/assets/plugins/jquery-3.4.1.min.js"></script>
<script src="~/assets/plugins/popper.min.js"></script>

<script src="~/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
</body>

</html>